### ISSUE TITLE
size

### ISSUE THREAD

**Issue by ghost** [jhalterman/expiringmap#16]
Is there a size limit or just time?
I need a combo that will take out the oldest when over.

**Comment by jhalterman** [comment]
Just time. Do you have any suggestions for how a size limit might look in the API?

**Comment by neevek** [comment]
I think it would be good for `ExpiringMap` to expose two APIs, one for user of this class to provide a `size calculator` to determine how much memory space will be occupied by the objects put in the map, another for setting max size of the map.

`ExpiringMap` will take both the time and the size into account to determine when to evict items in the map, i.e. whether some items expire or the total size exceeds the limit. By introducing the size limit, `ExpiringMap` probably needs to use LRU storage.

**Comment by jhalterman** [comment]
This sounds like a decent idea, though it's not something I'll probably have time to work on anytime soon. Do you have any API suggestions?

**Comment by jhalterman** [comment]
@neevek @puppetMaster3 Can you give me a better understanding of your use case where map entry size is a consideration, and what you're doing now to workaround this?

**Comment by neevek** [comment]
Without a size limit, the map can grow too big to fit in memory. 

Like I am using this map in a mobile app, the *expiring* feature of the map is awesome, it helps a lot to implement features that require cache with expiry time, in my application of the map, I only want to allocate a small portion of free memory to the map. I think the library would be more useful if this feature is implemented.

**Comment by jhalterman** [comment]
@neevek that makes sense. Would you be interested in limiting the total number of entries in the map, or just the total size of the entries? I'm also curious - how would you go about calculating the size of your entries?

**Comment by neevek** [comment]
Hi, @jhalterman 
I think limiting the total number of entries does not make much sense, because it can hold 1000 entries, each occupies 10 bytes, or 10 megabytes each, the number is the same, but the memory used is different.  
So it would be most useful to limit the size **in bytes**, and leave the calculation of the size of the entries to the user, like what I explained in my first comment, only by limiting size in bytes can it be possible for the memory to be controlled.

**Comment by bgalek** [comment]
@neevek still, simple size limit (number of entries) also should be available, for simpler apps or specific use cases when you're map grows faster then it's entries expires.

**Comment by Harry5573** [comment]
@neevek Perhaps a weight limit in that case similar to guava? See http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/cache/CacheBuilder.html#weigher(com.google.common.cache.Weigher), http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/cache/CacheBuilder.html#maximumWeight(long)

**Comment by neevek** [comment]
@Harry5573 Yes, something like that. What I was referencing is [this](https://developer.android.com/reference/android/util/LruCache.html), but I think the solution in Guava is better. With a `Weigher`, one does not need to override the map class, which is much less invasive.

**Comment by jhalterman** [comment]
I like the Weigher/maxWeight approach. It's pretty clean and should be straightforward to add.

If anyone would like to take a stab at a pull request for this, that would be great.

**Comment by vimalprakashts** [comment]
Is there any update on this ? This feature is good to have.

**Comment by ben-manes** [comment]
The design of a size bound requires tradeoffs, where you get to choose 2 of 3:
 1. Simple implementation
 2. Low time complexity
 3. High hit rate

While users would favor (2) and (3), an author might sacrifice one for simplicity. I think a first step is choosing the tradeoffs, after which we can offer design suggestions.

**Comment by axelfontaine** [comment]
@ben-manes That's not relevant here. As long as the builder interface stays constant in the future, the implementation can start simple and optimizations can be gradually introduced to remove performance bottlenecks.

First make it right, then make it fast.

**Comment by jhalterman** [comment]
I like @axelfontaine's suggestion of `maxSize`. It doesn't preclude other approaches for expiring things in the future, such as by weight.

Does anyone want to take a stab at a pull request for this? Basic approach: when `put` is called, if size >= maxSize, remove first entry in the map (`entries.first()`) before putting the new entry.

**Comment by axelfontaine** [comment]
Done. See #42

**Comment by ben-manes** [comment]
When I run #42 through a [simulator](https://github.com/ben-manes/caffeine/wiki/Simulator) it shows eviction occurs in FIFO order, as `ExpirationPolicy.CREATED` is the default. Changing to `ExpirationPolicy.ACCESSED` shows LRU order, as one would expect. You may want to document that side effect.

I can also run this through a JMH [benchmark](https://github.com/ben-manes/caffeine/wiki/Benchmarks) if desired.

**Comment by axelfontaine** [comment]
@ben-manes Second test added to demonstrate that the current implemention is correct for both `ExpirationPolicy.CREATED` and `ExpirationPolicy.ACCESSED`.

**Comment by ben-manes** [comment]
See this [benchmark](https://github.com/ben-manes/caffeine/blob/expiring_map/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/GetPutBenchmark.java#L44) for details and this [branch](https://github.com/ben-manes/caffeine/tree/expiring_map) if you'd like to run them yourself.

This compares against a synchronized `LinkedHashMap` in LRU mode. I suspect the slow performance is due to read-write locks being expensive and poorly scales under contention. A `StampedLock` might work better.

|Policy|Read|Read/Write|Write|
|---|---|---|---|
LinkedHashMap|7.7M/s|7.9M/s|7.2M/s
ExpiringMap (Lru)|1.0M/s|2.0M/s|2.5M/s
ExpiringMap (Fifo)|1.0M/s|1.9M/s|2.4M/s

**Comment by axelfontaine** [comment]
@ben-manes Since the pull request for this issue only literally changes 4 lines in the runtime logic (https://github.com/jhalterman/expiringmap/pull/42/files#diff-dce92a6a312d0d78dd21fab98a173b4cR1265) with no effect on locking, shouldn't the performance and contention discussion be moved to a separate issue instead?

**Comment by ben-manes** [comment]
Sure. I'm not against the PR and am only trying to help by giving so that you guys understand it's characteristics.

**Comment by jhalterman** [comment]
@ben-manes Thanks for the benchmark. I'm sure you're right re: the performance of a single read/write lock vs. lock striping (not sure what Caffeine does). I'll look into the `StampedLock` suggestion once the library moves to Java 8.

For now I'll consider this issue closed. I'm open to adding weight based expiration in the future similar to what [Caffeine supports](https://github.com/ben-manes/caffeine/wiki/Eviction#size-based) (if you want this, feel free to open another issue), but hopefully a straightforward `maxSize` support that @axelfontaine contributed will be good for most use cases.

**Comment by ben-manes** [comment]
The benchmarks are merged into master. Feel free to ping me if you'd like to discuss optimization ideas sometime. 

I wasn't intending to mention Caffeine, but you can read about the [design](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) ([slides](https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs/edit)). In short it uses a database-style write-ahead log to buffer and replay events to avoid lock contention. A future addition is variable expiration by using a hierarchical timer wheel so that it is performed in O(1) time (slide 10).

**Comment by jhalterman** [comment]
0.5.8 has just been released with this feature.

@ben-manes No worries. I came across Caffeine a while back and it looks awesome :)

**Comment by ben-manes** [comment]
@jhalterman You might be interested in my [TimerWheel](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java). It provides amortized O(1) variable expiration by cascading clocks, which are ring buffers of linked lists representing a time span. Currently it maxes out at 7 days, but in a more generalized version could overflow to a heap.

This approach could work well for you, if the O(lg n) scheduling has high overhead. When I had used a similar approach (around '08), the weak reference could result in a penalty due to bloating the `ScheduledExecutorService's` heap. A similar issue occurred with Guava's MapMaker, so we switched to fixed expiration using time-bounded LRUs (which I think you also did). I think a timer wheel is a decent middle ground between a priority queue and lazy expiration based on a size bound,

**Comment by jhalterman** [comment]
@ben-manes Indeed the reason I originally created ExpiringMap was because we were using Guava/Google Collections at the time (2009ish) and were hitting OutOfMemoryErrors since it used one TimerTask per entry. Switching to an LRU data structure with a single scheduled expiration for the head entry was the idea.

Thanks for the TimerWheel pointer. Will have a look when I get a chance :)
