### ISSUE TITLE
Combining variable expiration with lazy loading

### ISSUE THREAD

**Issue by hansenc** [jhalterman/expiringmap#17]
I'd like to be able to combine variable expiration with lazy loading. For example, creating an OAuth2 access token when needed and storing it for its lifetime (e.g. `expires_in`). I didn't see a way of doing this in the current API. 

Let me know what your thoughts are regarding the interface for this and I'm happy to submit a PR. I was thinking something along the lines of:
```java
ExpiringMap<String, OAuth2AccessToken > tokenMap = ExpiringMap.builder()
        .variableExpiration() //this may be redundant given the new type of loader
        .expiringEntryLoader(new ExpiringEntryLoader<String, OAuth2AccessToken>() {
            public ExpiringValue<OAuth2AccessToken> load(String key) { //key is unused in this case
              OAuth2AccessToken token = loadAccessToken();
              Duration expiresIn = token.getExpiresIn();
              return new ExpiringValue<>(token, expiresIn.getSeconds(), TimeUnit.SECONDS);
            }
        })
        .build();
```

**Comment by jhalterman** [comment]
I can't think of a better way to do this, and that API looks good to me. Sure, send over a PR! 

The only thing I'm wondering is if we should allow an EntryLoader and an ExpiringEntryLoader to be specified together. If we do, the first loader to be called would probably be the one that wins, unless it returned `null`. As for which loader to call first, probably the ExpiringEntryLoader since it's more specific. I think I'm fine with that unless you have any thoughts otherwise. And I do agree that specifying an ExpiringEntryLoader should implicitly enable variableExpiration (you can call this from within the builder).

Please include test(s) as you see fit. Thanks!

**Comment by jhalterman** [comment]
I just kicked out the 0.5.0 release that includes this work. It should hit maven central shortly.
